name: financial-tracker

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: Financial_Tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password123@db:5432/Financial_Tracker
    depends_on:
      - db

volumes:
  postgres_data: